services:
  load-reth0:
    image: ${LOAD_RETH_IMAGE:-docker.io/loadnetwork/load-reth:v0.1.2}
    container_name: load-reth0
    volumes:
      - ./rethdata/0:/data/load-reth
      - ./assets:/assets
    ports:
      - "8545:8545"
      - "8551:8551"
      - "9100:9001"
      - "30303:30303"
      - "30303:30303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/load-reth"
      - "--chain=/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=30303"
      - "--port=30303"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
  load-reth1:
    image: ${LOAD_RETH_IMAGE:-docker.io/loadnetwork/load-reth:v0.1.2}
    container_name: load-reth1
    volumes:
      - ./rethdata/1:/data/load-reth
      - ./assets:/assets
    ports:
      - "18545:8545"
      - "18551:8551"
      - "9101:9001"
      - "40303:40303"
      - "40303:40303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/load-reth"
      - "--chain=/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=40303"
      - "--port=40303"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
  load-reth2:
    image: ${LOAD_RETH_IMAGE:-docker.io/loadnetwork/load-reth:v0.1.2}
    container_name: load-reth2
    volumes:
      - ./rethdata/2:/data/load-reth
      - ./assets:/assets
    ports:
      - "28545:8545"
      - "28551:8551"
      - "9102:9001"
      - "50303:50303"
      - "50303:50303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/load-reth"
      - "--chain=/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=50303"
      - "--port=50303"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
  prometheus:
    image: prom/prometheus
    #image: prom/prometheus:v2.42.0 # Debian 12 seems to use a fairly old version of prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/data-prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
  #    command:
  #      - "--config.file=/etc/prometheus/prometheus.yml"
  #      - "--storage.tsdb.path=/prometheus"
  #      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
  #      - "--web.console.templates=/usr/share/prometheus/consoles"
  #      - "--no-storage.tsdb.wal-compression"
  #      - "--storage.tsdb.retention.time=1y"
  #      - "--storage.tsdb.no-lockfile"
  grafana:
    image: grafana/grafana-oss
    # Run as the invoking user to keep permissions consistent
    user: "${LOCAL_UID}"
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./monitoring/data-grafana:/var/lib/grafana
      - ./monitoring/config-grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/config-grafana/grafana.ini:/etc/grafana/grafana.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GF_LOG_LEVEL: info
      GF_ANALYTICS_ENABLED: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_ANALYTICS_FEEDBACK_LINKS_ENABLED: false
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards-data/default.json
      GF_USERS_DEFAULT_THEME: system
      GF_USERS_EDITORS_CAN_ADMIN: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
      GF_AUTH_BASIC_ENABLED: false
      GF_NEWS_NEWS_FEED_ENABLED: false
