[package]
name = "ultramarine-test-support"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
ultramarine-types.workspace = true

[lints]
workspace = true
