global:
  scrape_interval: 1s
scrape_configs:
  - job_name: "load-reth0"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ['load-reth0:9001']
        labels:
          client_name: "load-reth"
          client_type: "execution"
  - job_name: "load-reth1"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ['load-reth1:9001']
        labels:
          client_name: "load-reth"
          client_type: "execution"
  - job_name: "load-reth2"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ['load-reth2:9001']
        labels:
          client_name: "load-reth"
          client_type: "execution"

  - job_name: "malachite0"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ['ultramarine0:29000']
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite1"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ['ultramarine1:29001']
        labels:
          client_name: "malachite"
          client_type: "consensus"
  - job_name: "malachite2"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ['ultramarine2:29002']
        labels:
          client_name: "malachite"
          client_type: "consensus"
