---
loadnet_apt_disable_proxy: false
loadnet_apt_cache_valid_time: 3600
loadnet_apt_update_retries: 10
loadnet_apt_update_max_delay: 30
loadnet_apt_lock_timeout: 120

loadnet_docker_log_driver: "local"
loadnet_docker_log_max_size: "50m"
loadnet_docker_log_max_file: "5"

loadnet_el_http_bind: "0.0.0.0"
loadnet_el_http_api: "eth,net,web3,txpool,debug,trace"

# TxPool settings for high-throughput (10K+ TPS)
# Sizing heuristics: target_tps * buffer_seconds
#   - 10K TPS * 30 sec = 300K txs comfortable buffer
#   - 10K TPS * 50 sec = 500K txs for bursts
loadnet_el_txpool_pending_max_count: 300000
loadnet_el_txpool_queued_max_count: 300000
loadnet_el_txpool_max_pending_txns: 500000
loadnet_el_txpool_max_new_txns: 50000
loadnet_el_txpool_max_account_slots: 64
# Size limits in MB (blobs are ~128KB each, 6 blobs/tx = ~768KB)
# 2GB pending allows ~2600 blob txs or ~millions of regular txs
loadnet_el_txpool_pending_max_size: 2048
loadnet_el_txpool_queued_max_size: 2048
loadnet_el_txpool_gas_limit: 2000000000

loadnet_prometheus_bind: "127.0.0.1"
loadnet_prometheus_port: 9090
loadnet_prometheus_scrape_interval: "5s"

loadnet_grafana_bind: "127.0.0.1"
loadnet_grafana_port: 3000

loadnet_load_reth_uid: 10001
loadnet_load_reth_gid: 10001
loadnet_ultramarine_uid: 10002
loadnet_ultramarine_gid: 10002
loadnet_fix_ownership: true

loadnet_journal_max_use: "4G"
loadnet_journal_max_file_size: "200M"
loadnet_journal_max_retention: "7day"
loadnet_forward_journal_to_syslog: false
loadnet_syslog_max_size: "100M"
loadnet_syslog_max_files: 5
